---
- name: PHP | Check for Fast CGI INI
  stat: "path=/etc/php/{{ php_version }}/fpm/php.ini"
  register: phpfpm

- name: PHP | Check for CLI INI
  stat: "path=/etc/php/{{ php_version }}/cli/php.ini"
  register: phpcli

- include_tasks: php-fpm.yml
  when: phpfpm.stat.exists

- include_tasks: php-cli.yml
  when: phpcli.stat.exists

