- name: PHP | Check for custom INI files
  local_action: stat path="{{ files_dir }}/php"
  become: no
  register: ini_files

- name: PHP | Copy custom INI files
  become: true
  copy:
      src: "{{ files_dir }}/php/"
      dest: "/etc/php/{{ php.version }}/fpm/conf.d"
  when: ini_files.stat.exists
