---
- name: PHP | Add PPA
  apt_repository:
      repo: 'ppa:ondrej/php'

- name: PHP | Install FPM
  become: yes
  apt:
      pkg: "php{{ php.version }}-fpm"
      state: latest
      update_cache: yes

- name: PHP | Install Packages
  become: yes
  apt:
      pkg: "php{{ php.version }}-{{ item }}"
      state: latest
  with_items: "{{ php_packages }}"
  when: php_packages.0 is defined

